export const TIMAH_TOKEN_ABI = [
  "constructor(address initialOwner)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event BatchWhitelistUpdated(uint256 totalUpdated, bool isWhitelisted, address indexed updatedBy, uint256 timestamp)",
  "event EmergencyPauseTriggered(address indexed ownerAddress, string reason, uint256 timestamp)",
  "event EmergencyUnpauseTriggered(address indexed ownerAddress, uint256 timestamp)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event SecurityAnomalyDetected(address indexed target, string anomalyType, uint256 value, uint256 timestamp)",
  "event TokensBurned(address indexed burner, uint256 amount, uint256 newTotalSupply, uint256 timestamp)",
  "event TokensMinted(address indexed to, uint256 amount, address indexed caller, uint256 newTotalSupply, uint256 timestamp)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Unpaused(address account)",
  "event WhitelistUpdated(address indexed account, bool isWhitelisted, address indexed updatedBy, uint256 timestamp)",
  "function INITIAL_SUPPLY() view returns (uint256)",
  "function MAX_SUPPLY_CAP() view returns (uint256)",
  "function addToWhitelist(address account)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function batchAddToWhitelist(address[] accounts)",
  "function burn(uint256 amount)",
  "function burnFrom(address account, uint256 amount)",
  "function decimals() view returns (uint8)",
  "function flagSecurityAnomaly(address target, string anomalyType, uint256 value)",
  "function isWhitelisted(address account) view returns (bool)",
  "function mint(address to, uint256 amount)",
  "function mintWhitelisted(address to, uint256 amount)",
  "function name() view returns (string)",
  "function owner() view returns (address)",
  "function pause(string reason)",
  "function paused() view returns (bool)",
  "function removeFromWhitelist(address account)",
  "function renounceOwnership()",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function totalWhitelistedCount() view returns (uint256)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
  "function transferOwnership(address newOwner)",
  "function unpause()"
];
